version: '3.8'
services:
  db:
    image: mysql
    container_name: acme-testdb
    restart: always
    environment:
      MYSQL_DATABASE: 'acme-testdb'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    networks:
      - acme-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  mymobileworker-application:
    build: .
    image: bahadockerhub/mymobileworker
    ports:
      - "8000:8000"
    networks:
      - acme-network
    depends_on:
      - "db"
networks:
  acme-network:
    name: acme-network
    driver: bridge